version: "3.0"
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    networks:
      - wiki-net
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME : ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD : ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${DB_NAME}:27017/
    depends_on:
      - mongodb
    networks:
      - wiki-net
  web:
    build: .
    command: sh -c "python wiki_wordcount.py && uvicorn wikifastapi.main:app --host 0.0.0.0"
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    networks:
      - wiki-net
networks:
  wiki-net:
    driver: bridge
